[package]
name = "lovm"
version = "0.1.0"
authors = ["lausek <root@lausek.eu>"]
edition = "2018"

[lib]
name = "lovm"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.2"
